### ISSUE TITLE
New fork of mopidy-youtube

### ISSUE THREAD

**Issue by natumbri** [natumbri/mopidy-youtube#103]
Hi,

I made a new fork, over at https://github.com/natumbri/mopidy-youtube/

- It is based on the higher performance fork at https://github.com/chatziko/mopidy-youtube/tree/performance-improvements-3
- It uses youtube_dl instead of pafy
- It implements a new default backend (called scrAPI) that doesn't use the Google API, instead using regex to scrape YouTube search results.  Use of the Google API can be enabled in config, in which case a valid API key must be supplied
- It adds a number of configuration options
- It respects mopidy's proxy configuration

Haven't tested it much, but it seems reasonably workable, including on pretty basic hardware.  My testing has (exclusively) been on my H3 based nanopi M1 (512M) running Armbian. 

No idea how robust the regex stuff is - not very, I'd say. 

There's a bug with thumbnails for playlists, but it doesn't seem to affect the music. 
Who knows what other bugs there are - many I'm sure. If you notice one, open an issue at [natumbri/modipy-youtube](/natumbri/mopidy-youtube/issues). 

To install it, it is necessary to first get a working version of the standard mopidy-youtube working, and then copy over the top of it. I'll maybe work out how to get a proper install process together one day.  Make sure you are using the latest version of youtube_dl.

Cheers
Nik

**Comment by kingosticks** [comment]
Have you considering becoming the maintainer of this extension? We need one.

**Comment by natumbri** [comment]
Nope. What would that entail? I don't really know anything about writing
code (except for Google+stackoverflow+cut+paste) or being a 'maintainer'. I
just like being able to play tunes from YouTube on my hifi...

Cheers
Nik

**Comment by natumbri** [comment]
@kingosticks I've had a look and I think the version I've made based on the one @chatziko made fixes (or at least advances) many of the open issues (including *the* big one: unauthorized use of the Google YouTube API). But I haven't previously been involved in a git project and don't really know anything about, for example, publishing a new version of something to PyPl. I'd be interested in becoming maintainer, but wouldn't want to break anything, and would probably need a bit of hand holding. Let me know if you think the burden for the project of supporting a newbie maintainer would be better than the status quo. If you are interested, I could submit a couple of *very* basic changes to the project (eg moving hard-coded options to the config file), to qualify...

**Comment by kingosticks** [comment]
We've all got to start somewhere. If you are interested, starting with a simple config setting change sounds good. It'll be worth having a read through our development docs, in particular:
* https://docs.mopidy.com/en/latest/contributing/
* https://docs.mopidy.com/en/latest/codestyle/

**Comment by giltwist** [comment]
I'm willing to beta test, how do I switch to the new fork?

**Comment by natumbri** [comment]
@giltwist At this stage, I think the easiest thing for you to do would be to install the development fork from mopidy/mopidy-youtube, and apply the changes that are at  https://github.com/natumbri/mopidy-youtube/tree/scrAPI (possibly - if you don't know a better way to do it - by just saving the files from my fork over the top of the installed files...) .  You'll also need to put all the relevant configuration parameters into your config file.

I am trying to become the maintainer of this project, but I am on a pretty steep learning curve, in particular with respect to github, which I've never really used before.  I need to clock up a couple of good commits before that can happen, and I made a real mess of the first one I tried.  I think the actual changes are finally where I wanted them to be, but it has been a bit of a journey to get there.  And it appears to have failed some automatic test - I'm not sure what that test is or how it works or what the implications of failing it are.  Hopefully @kingosticks and @brammittendorff-dd (and anyone else who wants to!) can continue to support me to get on top of these things.

For what it is worth, the scrAPI fork that I made is working well for me, in its scrAPI and API forms.  In scrAPI form, it can be a bit slow at certain things - for example playing a playlist takes a pretty long time - but it generally seems to get there in the end.

**Comment by natumbri** [comment]
@seth-- and @stekern you may be interested to have a look at the fork I've made. I just noticed the work that you to have done in #92 and am interested to see how you've approached it

Cheers
Nik

**Comment by natumbri** [comment]
@eseca and @tfilo The fork I've been working on can load playlists without an API key - this may resolve the problems described in #91

**Comment by KristerV** [comment]
Okay so this is what I did:
1. Install mopidy-youtube from AUR repo
2. Overwrite install files with https://github.com/natumbri/mopidy-youtube/ branch `develop` since those changes were most recent
3. Enter Youtube API Key that I made
4. Run Mopidy and search on localhost:6680/moped
5. Result: nothing. Results are empty in the browser and terminal reports
```
INFO     youtube LibraryProvider.search "{u'any': [u'chalice']}"
INFO     Searching YouTube for query "chalice"
```
No other errors unfortunately.

I wonder if there's anything else I can do. I am a dev, but unsude how to debug this.

**Comment by natumbri** [comment]
Oh yeah - the develop branch will definitely not work without a valid API key. The version in scrAPI can be configured to work without the API. Just set api_enabled=false. It is slower, but it works (for me so far - I'm not sure if anyone else has used it)...

Cheers
Nik

**Comment by B3N4K** [comment]
Hi,

Your fork looks interesting for me. However, the branch scrAPI is gone (404 Not Found), the branch `feature/implement-scrAPI` doesn't work for me (bunch of exceptions and whole mopidy freezes when adding song). And your repo doesn't seem to have issues enabled either. Are you still working on the fork? If so, is there any working branch?

Thanks!

**Comment by natumbri** [comment]
Thanks @B3N4K.  Glad the proxy branch is working for you. I personally use the scrAPI branch, without trouble. It's hard to know what problem you're running into without more details. I'll try to enable issues on my repo. Did you get a working Google API key?

Thanks, 
Nik

**Comment by B3N4K** [comment]
Hi,

1) When you say that scrAPI branch works for you, do you mean [feature/implement-scrAPI](https://github.com/natumbri/mopidy-youtube/tree/feature/implement-scrAPI)? Because there is no scrAPI branch in your project on gitlab - the [link you posted earlier](https://github.com/natumbri/mopidy-youtube/tree/scrAPI) gives [404 Not Found](https://i.imgur.com/h4TXdVj.png).

2) When i use `api_enabled = false`, the plugin works but there are no song durations displayed - prolly a parsing error. First i thought it might be related to youtube being in different language (as your plugin might have issues scraping the youtube page for anyone from non-english speaking country as their youtube responses will be in different language and might look differently), but i fixed that with adding following line before the .get():

```
scrAPI.session.headers.update({'Cookie': 'PREF=hl=en;', 'Accept-Language':'en;q=0.8'})
```

Unfortunately, even though youtube result is now in english and does finally contain the 'Duration:' string you are looking for (instead of its regional translation), the durations are still not displayed.

3) The previous problem i have is very expected and will be popping up all the time - scraping a webpage like youtube is not only against its TOS (whatever), but won't really work that great - the webpage is quite possibly different in different parts of world (not only translation-related, but also possibly other minor changes resulting from local laws - for example cookie consent should be present in EU but is not required in other parts of the world - so the page may be different for people around the world). Moreover, one day Youtube will change its results page for everyone and you won't be around cuz this project wont be of interest for you anymore (inevitable that you will get tired of constantly updating the regexes and abandon this project sooner or later - maybe years from now, but still, it will come) and that will lead to the scraping part to not work.

Therefore, i would personally like to avoid scraping at all and use the API (which is guaranteed to not change in a way that would break currently existing scripts - legacy support is guaranteed and if they wanted to change the API in a dramatic way, they would have to create a new `v4` endpoint instead of breaking `v3` for everyone using it. Personally i see no reason not to use the API. You can get the API key easily and for free so i see really no reason to use the scraping approach.

4) My API key is correct (works perfectly fine with current official upstream - which unfortunately is super slow and doesn't work if there is "live event" video in the results - for example if you currently search for "danheim", one of the results will contain "live event" (or at least in my country it will - other countries get different search results tailored for that region so might be fine for someone else)). However, when i have `api_enabled = true` and i search for videos, i get following exception:

```
2019-05-29 09:03:38,905 INFO [8181:YouTubeBackend-6] mopidy_youtube: youtube LibraryProvider.search "{u'any': [u'danheim']}"
2019-05-29 09:03:38,944 INFO [8181:YouTubeBackend-6] mopidy_youtube: Searching YouTube for query "danheim"
2019-05-29 09:03:39,691 ERROR [8181:Thread-16] mopidy_youtube: youtube thread error: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy_youtube/youtube.py", line 663, in worker
    f(*args)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_youtube/youtube.py", line 203, in job
    video._set_api_data(fields, dict.get(video.id))
  File "/usr/local/lib/python2.7/dist-packages/mopidy_youtube/youtube.py", line 165, in _set_api_data
    + int(m.group('seconds') or 0))
AttributeError: 'NoneType' object has no attribute 'group'
```

I still get the search results though. Then if i add a song to be played, following message will be displayed in logs and whole mopidy will freeze forever:

```
2019-05-29 09:03:57,709 INFO [8181:YouTubeBackend-6] mopidy_youtube: youtube LibraryProvider.lookup "youtube:video/Danheim - Ulfhednar.c6MczzFi67M"
```

**Comment by natumbri** [comment]
Thanks @B3N4K - I've opened up a couple of issues over on my fork, reflecting what you've said above.  I'll have a look when I get a chance.  Might be a good idea to take any further discussion over there.

That session.headers.update is a good tip. I probably should put in as many headers as I can, to try to standardise responses and give the scraping routines the best chance of working.

As far as not using scraping goes, I agree with you that the API is better, for the issues you have identified. It is also faster. I, personally, use the plugin with `api_enabled = true` and a valid key.  I just thought a scraping version might be useful for people who don't want to get an API key.

**Comment by sebsebmc** [comment]
I tried both feature/implement-scrAPI and feature/proxy today by directly queuing a uri and the metadata seemed to load but the mopidy did not actually play the audio. I saw in the debug log that it entered the stop state at 0 seconds. Same behavior in both branches.

**Comment by Mic92** [comment]
For the non-developers here is what you need to do use this fork with API keys:

First create an API key for `YouTube Data API v3` as described in https://developers.google.com/youtube/v3/getting-started#before-you-start

Then append the API key to you mopidy configuration in `~/.config/mopidy/mopidy.conf` as well as the `api_enabled` flag:

```
[youtube]
youtube_api_key = AI0000000000000000000000000000000000000
api_enabled = true
```

**Comment by Mic92** [comment]
It may be a good idea to log the whole error in this line: https://github.com/natumbri/mopidy-youtube/blob/2bc6338cb2933cd4df2f67ee5dce42f1e4f9eaea/mopidy_youtube/backend.py#L80 as it might contain useful information why an API key does not work.

**Comment by francoisgouet** [comment]
Hello, tested with mopidy-party, musicbox_webclient and Cantana client and searches only appear in the logs and stops at the slightest empty field.

ERROR map error"'channelTitle'"                                                   
WARNING YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.

**Comment by natumbri** [comment]
Hi @francoisgouet.

Thanks for the feedback and sorry to hear that it is not working for you. I'm not familiar with mopidy-party, musicbox_webclient or Cantana. 

Perhaps open an issue over on my fork, with some more information (like which branch of mopidy-youtube you are using, how you have configured it, which version of mopidy you are using, a testable example of a search that fails and verbose logs). With that information, I might be able to assist.

I use my fork of mopidy-youtube every day and it is generally working pretty well for me. But my use case is pretty limited - search for tracks in Rompr and play them.

Cheers
Nik

**Comment by natumbri** [comment]
Hi @francoisgouet - just following up, I was able to search, queue and play songs from youtube using both mopidy-party and musicbox_webclient. I didn't try Cantana.  Given the other two work, it sounds like it might be something about the way my version of mopidy-youtube interacts with your configuration.

Cheers,
Nik

**Comment by natumbri** [comment]
Mopidy-YouTube is getting 'autoplay' functionality - see #141
