### ISSUE TITLE
Playlists are not fully loaded

### ISSUE THREAD

**Issue by Dzordzu** [natumbri/mopidy-youtube#129]
## Version
3.0a1

## Frontend 
Mopidy-MusicBox-Webclient: 3.0.1
(streams)

## Problem
Only 50 elements are loaded (instead of the entire playlist)
Limits of the playlist are set to `2000`

## Possible source of problems
https://github.com/natumbri/mopidy-youtube/blob/c94584138c8057a95c646528fe32be950b1d18a8/mopidy_youtube/youtube.py#L195-L199

**Comment by Dzordzu** [comment]
Checked it locally. Increasing limit does not work

**Comment by natumbri** [comment]
That's strange!

Are you using a working API key and the API backend? Or the bs4 backend? 

The bs4 backend can only return a maximum of 100 songs in a playlist; but that doesn't explain why only 50 are returned when you set the max to 2000. 

There should be no limit for the API backend.

Are you able to give an example of a playlist where it is happening for you, and also post your config?

**Comment by natumbri** [comment]
Try the new [fix/issue-129 branch](/natumbri/mopidy-youtube/tree/fix/issue-129).

Should give you up 100 items in a playlist for the non-API version (because I don't know how scroll the search results that youtube returns past the 100th result); I don't think there is a maximum for the API version.

Would be interested to know if it (a) works and, if it does (b) how the performance is.  It would be great if you could try (and report back on) both with the API and without the API.

Thanks!

**Comment by Dzordzu** [comment]
Well. Something strange happened. I tried to reinstall it (without fix), and it started woking without any problems. I can assume that it was the problem of the installation (I had mopidy-yt v2 and v3 installed at once - one from the aur, and the other one from the pip). Maybe it was the cause of this two issues? 
I'll try your fix later.
Btw. thanks for bringing this project back to life! I'm really thankful:)

**Comment by natumbri** [comment]
@Dzordzu thanks - if you do try the fix, it should now return all the items, up to the maximum you specify, in both API and non-API configurations.
