### ISSUE TITLE
Started getting mopidy_youtube list_videos error ""

### ISSUE THREAD

**Issue by mgrouch** [natumbri/mopidy-youtube#229]
Started getting mopidy_youtube list_videos error ""

I didn't change me set-up which worked before just recently.

Thanks

**Comment by mgrouch** [comment]
whole mopidy server stops responding to http requests after that

**Comment by mgrouch** [comment]
see also 

https://github.com/mopidy/mopidy/issues/2056

**Comment by mgrouch** [comment]
same issue exists after upgrading to 3.6 version

**Comment by natumbri** [comment]
Thanks for the report - that is odd, it is working for me.

In https://github.com/mopidy/mopidy/issues/2056 you say:

> **How to reproduce**
> Visit youtube videos playlist

What do you mean by 'visit'?  What are the steps you take to 'visit' a playlist?

Cheers,
Nik

**Comment by mgrouch** [comment]
I just click on playlist in musicbox or iris. 
Result is same.

**Comment by natumbri** [comment]
Thanks - because this is not happening for me, if I'm going to be able to help you, you're going to need to describe what you do in pretty careful detail. What playlist? Click where?

**Comment by Chreece** [comment]
I'm getting:
`ERROR    [ThreadPoolExecutor-4_0] mopidy_youtube list_videos error "'videoPrimaryInfoRenderer'"`

I have playlists added to mopidy that contain exclusively youtube playlists. Since update to 3.6 I can't play any of the playlists. Mopidy get stuck. The other plugins (Mixcloud etc) are working ok. 
I tried to search through IRIS a youtube playlist and play it afterwards which also got to crash mopidy
Reverting to 3.5 doesn't change anything

Edit: I was on youtube_dl pluging, tried yt-dlp, same results...
During the troubleshoot to find what's causing the crash, after restarting mopidy and try to play a playlist from my IRIS playlists one of them outputs sound but the mopidy still crashes ( doesn't respond on commands )

Final edit:

The problem is definetly on v3.6
I did a sudo uninstall 3.6 and sudo install 3.5 and everything works as before...
The error is still there but mopidy doesn't crash

**Comment by natumbri** [comment]
Can you post links to some not working playlists?

**Comment by mgrouch** [comment]
Example

https://github.com/bareboat-necessities/lysmarine_gen/blob/buster/install-scripts/4-server/files/BBN-Playlist.m3u8

**Comment by natumbri** [comment]
Thanks.

`youtube:video/WILLY WILLIAM FEAT NATTY RICO MIKA V - Le Tour Du Monde (Album Edit).doNlCgv-wNs` is private. I think that is the problem.  Looks like it needs to handle inaccessible playlist items more gracefully.

Any playlists that _don't_ include private videos that don't work?
