### ISSUE TITLE
Search speed solution

### ISSUE THREAD

**Issue by NellyWhadsDev** [natumbri/mopidy-youtube#27]
Hey there,

I saw an issue open here about the issue of the latency of search in this extension. I see that using the google API may be the cause of this lag, but is it possible to use this API instead?

https://www.mashape.com/zazkov/youtube-grabber#search-video-php

It has a python component and may make search much faster.

If there's anything I can do to help shoot me a hollar - I'd love to help out as I'm working on some mopidy front end ideas and having Spotify as the only fast and consistent source of audio is slightly upsetting :)

 -- NellyWhads

**Comment by muhahacz** [comment]
+1

**Comment by elsurudo** [comment]
Agreed. On my RasPi, this plugin is actually totally unusable because of the search speed. It seems to block the whole mopidy server while searching, and then finally times out a couple of minutes lated. Maybe mine is a special case – perhaps I'll create a more detailed ticket once I have more time to try it out again.

**Comment by kingosticks** [comment]
Have you tried https://github.com/mopidy/mopidy-youtube/pull/46 ?
