### ISSUE TITLE
Broken test: test_lookup_video_uri

### ISSUE THREAD

**Issue by jodal** [natumbri/mopidy-youtube#70]
We have a broken test, ref. https://travis-ci.org/mopidy/mopidy-youtube/jobs/170598658, which seems to have been broken since de0507390d841fb2f382fa36559eb7b78c064769 almost a year ago.

@jcass77 Can you have a look at the test?

**Comment by jcass77** [comment]
I'm stumped on this one. It looks like the test is failing due to a missing ``youtube-dl`` dependency.

pafy 0.5.0 [made youtube-dl optional](https://github.com/mps-youtube/pafy/blob/a4343a2b79967d9da79b6c2029afed2bf5aa3748/setup.py#L26-L28), although using it is still recommended.

I thought that just changing ``setup.py`` to include ``install_requires=['pafy[youtube-dl-backend] >= 0.5.0',`` would fix the issue but it doesn't.

Even more perplexing is the fact that doing a manual ``pip install youtube-dl`` before running the tests locally makes everything green (i.e. ``sitepackages = true`` picks up the manually installed dependency). But if we rely on tox and / or setup.py to install the extra dependency it fails.

Any ideas?

**Comment by natumbri** [comment]
I don't think this is a problem anymore, so I'm closing.
