### ISSUE TITLE
Key Error: "u'items'" 

### ISSUE THREAD

**Issue by rkkoszewski** [natumbri/mopidy-youtube#87]
Hi, I recently tried to find a youtube video from Mopidy with this plugin, and it seems to crash the whole search feature from Mopidy with a "Key Error: "u'items'" exception. The plugin has been working fine before on my Mopidy setup, and I haven't changed anything so far, so it's probably a Youtube side issue?

Just in case I updated _pafy_ and the _mopidy-youtube_ but the issue is still present. 

Here is the Traceback. 

```
"Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/internal/jsonrpc.py", line 133, in _handle_single_request
    result = self._unwrap_result(result)
  File "/usr/lib/python2.7/dist-packages/mopidy/internal/jsonrpc.py", line 222, in _unwrap_result
    result = result.get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 347, in search
    result = future.get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_youtube/backend.py", line 192, in search
    tracks=search_youtube(search_query)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_youtube/backend.py", line 102, in search_youtube
    playlist = [item['id']['videoId'] for item in data['items']]
KeyError: u'items'
"
```

**Comment by custozza** [comment]
same problem here. Beside they fact that I just installed everything and that it therefore never worked for me :-(

**Comment by ajoshpratt** [comment]
It looks like the issue stems from an API key issue.  There's no 'items' in the data dictionary because the API call itself is returning an error, stating that the key in use is disabled or has never been used.

`{u'error': {u'code': 403, u'message': u'Access Not Configured. YouTube Data API has not been used in project 119103001349 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=119103001349 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.', u'errors': [{u'domain': u'usageLimits', u'message': u'Access Not Configured. YouTube Data API has not been used in project 119103001349 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=119103001349 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.', u'reason': u'accessNotConfigured', u'extendedHelp': u'https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=119103001349'}]}}`

I worked around this on my machine by registering an API with google and just changing the key (line 23) in mopidy_youtube/backend.py . Not sure that's a good long-term solution, though.

**Comment by custozza** [comment]
@ajoshpratt thx for the reply. I'll try it as soon as I find time. Maybe it would be good to add the API key as config parameter in the ext.conf?

**Comment by tfilo** [comment]
Hello, I have same issue. @ajoshpratt your solution looks promissing. Can be good idea to change backend.py to read API key from config file ? After that everybody can easily setup their key.

**Comment by tfilo** [comment]
@custozza I was thinking about the same. If there will be API key in config, it could work just fine. I will try it later today and if it will work on my mopidy I can make merge request.

**Comment by kingosticks** [comment]
@dz0ny could you have a quick look what happened to the API key? Did we exceed the usage restrictions?

**Comment by tfilo** [comment]
I created pull request but if you like you can use source code from my fork too.
https://github.com/mopidy/mopidy-youtube/pull/88

**Comment by custozza** [comment]
@tfilo thx for the work
however i get following error
git clone https://github.com/mopidy/mopidy-youtube.git
Cloning into 'mopidy-youtube'...
fatal: unable to access 'https://github.com/mopidy/mopidy-youtube.git/': Couldn't connect to server

I am quite inexperienced when it comes to git :-(

**Comment by tfilo** [comment]
@custozza If you want to clone my fork you need to do:
git clone git@github.com:tfilo/mopidy-youtube.git
or if you like to clone original repository you need to do:
git clone git@github.com:mopidy/mopidy-youtube.git

**Comment by custozza** [comment]
@tfilo 
just had to reboot the system ... network problems due to connection lose of the wlan ... 
but thx

**Comment by tfilo** [comment]
@custozza 
I usually clone through ssh format, but then I tried yours and found out it works too.

**Comment by custozza** [comment]
@tfilo dude you are my hero :-) everything is working perfectly now. Great work. Can I somehow up vote your pull request to give it more priority?

**Comment by tfilo** [comment]
@custozza thank you, I think we just need to wait. But there is problem on my pull request "The Travis CI build failed" and I don't understand why. So i doubt that it will be merged by someone.

**Comment by kingosticks** [comment]
The Travis failure is not related to your change. But you'll notice this extension has no maintainer i.e. it's not a priority issue.

**Comment by kingosticks** [comment]
Another PR to fix the build problem and you'd have qualified! :)

**Comment by tfilo** [comment]
@kingosticks I have no experience with Travis and only little experience with Python. But I am programming in other languages and I am familiar with Jenkins. So it can be good opportunity to learn python syntax and extend my knowledge of programming languages and continuous integration tools. I will look at it in my free time.

**Comment by tfilo** [comment]
I closed #88 because it was on develop branch, so I wasn't possible to create separate fix for test because there was already changes from #88 in my fork. So I created new pull request from separate branch:
https://github.com/mopidy/mopidy-youtube/pull/89

and I created this separed branch with fix on current branch

https://github.com/mopidy/mopidy-youtube/pull/90

and as I said I am only beginning with python so I don't know if I can be good maintainer for this plugin. But since I use mopidy and this plugin on raspberry I will do my best to keep it working and fastest as possible. I looked into issues on this project. I am not able to fix all of them. If I will be maintainer, i will try to merge this PR since it can improve performance https://github.com/mopidy/mopidy-youtube/pull/61 , https://github.com/mopidy/mopidy-youtube/pull/72 and https://github.com/mopidy/mopidy-youtube/pull/82 . I don't see much point in other PR because it looks duplicate or included these three. So If you like me to ask to be a maintainer. I will make PR to README to add me as maintainer. I will glad to help in best way I can.

**Comment by tfilo** [comment]
I closed my PR because acording to this #92 lot out user can lost their accounts if they try to get own API key.

**Comment by alfaktulu** [comment]
excuse me, what's the solution?

**Comment by alfaktulu** [comment]
if I use another yt_key?? This is the real solution... or not?
mps-youtube for example... :-)

**Comment by ajoshpratt** [comment]
If you use another youtube key, as mentioned above, you run the very serious risk of having your whole Google account deactivated.  Not something you want, I think.  So it's definitely not a good solution.

There's another issue here which tries to discuss possible solutions, I believe.

**Comment by KuenzelIT** [comment]
Is there anything new on this? Or is it just that this is never gonna work because of Google's policies?

**Comment by weilbith** [comment]
Besides the discussion of using your own key at the risk of being banned:
What do you think about making the search functionality of this backend optional?
For example does I like to listen to long music mixes without the useless need to render the video in a browser tab and losing the control over my music output with MPD at once. So I search my music in old fashion on the platform by the best thumbnail and add it to the Playlist. ;)
Unfortunately even this usage would not correlate with the API key problem, I can't use the library tab of my client anymore, since blocks by this error all the time.
So either we introduce another option to toggle the search or we build it on top the API key option which, if set enable this functionality (default key would be not allowed anymore here).
To be honest I'm not aware about the backend interface, so I'm not sure what happens if a simple `if`-statment at the top of the function terminates the function. I guess it needs then an empty list or so.
